services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - ./:/var/www/html # Ruta corregida para WSL
    working_dir: /var/www/html
    networks:
      - symfony_network
    environment:
      - PHP_XDEBUG_MODE=off
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite la comunicación con el host de Windows

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
